ADB_COMMAND_APPS = "ls \"sdcard/Android/data\""
ADB_COMMAND_BUGREPORT = 'bugreport'
ADB_COMMAND_CLEAR = "shell pm clear {}"
ADB_COMMAND_CLOSE = "shell am force-stop {}"
ADB_COMMAND_CONNECT = "connect {}:{}"
ADB_COMMAND_DEVICES = 'devices'
ADB_COMMAND_GET_STATE = 'get-state'
ADB_COMMAND_GETSERIALNO = 'get-serialno'
ADB_COMMAND_INPUT_TEXT = "shell input text {}"
ADB_COMMAND_SWIPE = "shell input swipe {} {} {} {} {}"
ADB_COMMAND_KEYEVENT = "shell input keyevent {}"
ADB_COMMAND_TAP = "shell input tap {} {}"
ADB_COMMAND_INSTALL = "install {} {}"
ADB_COMMAND_KILL_SERVER = 'kill-server'
ADB_COMMAND_LAUNCH = "shell am start {} {}/.{}"
ADB_COMMAND_OS_VERSION = "shell getprop ro.build.version.release | tr -d \'\\r\'"
ADB_COMMAND_PACKAGES = "shell pm list packages -f | sed -e 's/.*=//' | sort"
ADB_COMMAND_PREFIX = 'adb'
ADB_COMMAND_PULL = 'pull {} {}'
ADB_COMMAND_PUSH = 'push {} {}'
ADB_COMMAND_RM = "shell rm -r {}"
ADB_COMMAND_START_SERVER = 'start-server'
ADB_COMMAND_TESTS = "shell am instrument {} {}/android.support.test.runner.AndroidJUnitRunner"
ADB_COMMAND_UNINSTALL = "uninstall {}"
ADB_COMMAND_VERSION = 'version'
ADB_COMMAND_WAITFORDEVICE = 'wait-for-device'